"""add estado unidad to productos

Revision ID: 021d959bc3bc
Revises: 359b32ca59c4
Create Date: 2026-06-18 14:26:30.142255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021d959bc3bc'
down_revision = '359b32ca59c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad', sa.String(length=10), nullable=False, server_default='UND'))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=False, server_default='ACTIVO'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('unidad')

    # ### end Alembic commands ###
