"""Cambiar estado de cliente a Enum

Revision ID: 07355e10326d
Revises: 878d0947d8ac
Create Date: 2026-07-29 12:39:52.914990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07355e10326d'
down_revision = '878d0947d8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('ACTIVO', 'INACTIVO', name='estadocliente'),
               existing_nullable=True)

    op.execute("UPDATE clientes SET estado = 'ACTIVO' WHERE estado = '1'")
    op.execute("UPDATE clientes SET estado = 'INACTIVO' WHERE estado = '0'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', name='estadocliente'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
