"""Remove unidad from producto

Revision ID: 2a1dac0c398f
Revises: 28d46535b470
Create Date: 2026-07-14 14:54:11.184274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1dac0c398f'
down_revision = '28d46535b470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('unidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad', sa.VARCHAR(length=10), server_default=sa.text("'UND'"), nullable=False))

    # ### end Alembic commands ###
