"""add client fields

Revision ID: 359b32ca59c4
Revises: 6a9c19ed2e43
Create Date: 2026-06-17 09:48:40.791778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359b32ca59c4'
down_revision = '6a9c19ed2e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_unique_constraint('uq_clientes_codigo', ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clientes_codigo', type_='unique')
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('ciudad')
        batch_op.drop_column('email')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
