"""Agregar municipio

Revision ID: 3a47e41b0382
Revises: 64ccd2b3d1eb
Create Date: 2026-07-30 17:06:09.740614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a47e41b0382'
down_revision = '64ccd2b3d1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipio', sa.String(length=100), nullable=False, server_default='No Especificado'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('municipio')

    # ### end Alembic commands ###
