"""add debe cambiar password usuario

Revision ID: 4840cfd6cb69
Revises: 4c58f2587524
Create Date: 2026-06-29 11:22:41.959551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4840cfd6cb69'
down_revision = '4c58f2587524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('debe_cambiar_password')

    # ### end Alembic commands ###
