"""add referencia to pagos

Revision ID: 4c58f2587524
Revises: f343dc781ad2
Create Date: 2026-06-26 11:22:12.924235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c58f2587524'
down_revision = 'f343dc781ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referencia', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_column('referencia')

    # ### end Alembic commands ###
