"""Cambiamos a 8 digitos el numero de telefono

Revision ID: 566dc66c7121
Revises: cfa5bf8d5c28
Create Date: 2026-07-06 15:40:01.217854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566dc66c7121'
down_revision = 'cfa5bf8d5c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
