"""Agregar tabla proveedores

Revision ID: 64ccd2b3d1eb
Revises: 07355e10326d
Create Date: 2026-07-30 16:41:36.443434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ccd2b3d1eb'
down_revision = '07355e10326d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('nombre_proveedor', sa.String(length=150), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('ruc', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estadoproveedor'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('ruc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedores')
    # ### end Alembic commands ###
