"""Limpieza modelo cliente

Revision ID: 878d0947d8ac
Revises: fd1f590f2887
Create Date: 2026-07-29 11:17:34.493848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878d0947d8ac'
down_revision = 'fd1f590f2887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('apellidos')
        batch_op.drop_column('direccion')
        batch_op.drop_column('fecha_ingreso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ingreso', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('apellidos', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
