"""Agregar relacion producto proveedor

Revision ID: 91129571e17a
Revises: 3a47e41b0382
Create Date: 2026-07-31 08:18:59.456152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91129571e17a'
down_revision = '3a47e41b0382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_productos_proveedor_id', 'proveedores', ['proveedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_productos_proveedor_id', type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    # ### end Alembic commands ###
