"""refactor_producto

Revision ID: b0147e10ad04
Revises: d1b3beca0e1a
Create Date: 2026-07-31 16:31:33.544084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0147e10ad04'
down_revision = 'd1b3beca0e1a'
branch_labels = None
depends_on = None


def upgrade():
    # Asegurar integridad de datos antes de alterar la estructura en SQLite
    op.execute("UPDATE productos SET estado = 'ACTIVO'")
    op.execute("UPDATE productos SET proveedor_id = (SELECT MIN(id) FROM proveedores) WHERE proveedor_id IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVO', 'INACTIVO', name='estadoproducto'),
               existing_nullable=False)
        batch_op.alter_column('proveedor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('proveedor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', name='estadoproducto'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
