"""add discount fields to sale detail

Revision ID: bca95b564ffb
Revises: 566dc66c7121
Create Date: 2026-07-07 11:33:07.202138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca95b564ffb'
down_revision = '566dc66c7121'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'descuento_porcentaje',
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default='0'
        ))
        batch_op.add_column(sa.Column(
            'descuento_monto',
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default='0'
        ))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'descuento_maximo',
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            server_default='0'
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('descuento_maximo')

    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_column('descuento_monto')
        batch_op.drop_column('descuento_porcentaje')

    # ### end Alembic commands ###
