"""Venta model to Enum

Revision ID: c7c6cee13a2b
Revises: 37ef7b9aecb3
Create Date: 2026-08-04 16:49:01.035894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c6cee13a2b'
down_revision = '37ef7b9aecb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVO', 'INACTIVO', name='estadoproducto'),
               existing_nullable=False)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('precio_compra',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('precio_venta',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('tipo_venta',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CONTADO', 'CREDITO', name='tipoventa'),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVA', 'ANULADA', name='estadoventa'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ACTIVA', 'ANULADA', name='estadoventa'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('tipo_venta',
               existing_type=sa.Enum('CONTADO', 'CREDITO', name='tipoventa'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio_venta',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('precio_compra',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', name='estadoproducto'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
