"""add codigo and stado to category

Revision ID: cd69a581a079
Revises: 021d959bc3bc
Create Date: 2026-06-19 13:57:54.694919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd69a581a079'
down_revision = '021d959bc3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=False, server_default='ACTIVO'))
        batch_op.create_unique_constraint('uq_categorias_codigo',
    ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('uq_categorias_codigo',
    type_='unique')
        batch_op.drop_column('estado')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
