"""unique numero de telefono

Revision ID: cfa5bf8d5c28
Revises: 4840cfd6cb69
Create Date: 2026-07-06 15:29:32.854327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa5bf8d5c28'
down_revision = '4840cfd6cb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_clientes_telefono',
            ['telefono'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clientes_telefono', type_='unique')

    # ### end Alembic commands ###
