"""estado_categoria_enum

Revision ID: d1b3beca0e1a
Revises: 91129571e17a
Create Date: 2026-07-31 10:11:26.033775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b3beca0e1a'
down_revision = '91129571e17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('ACTIVO', 'INACTIVO', name='estadocategoria'),
               existing_nullable=True)

    # Convertir datos manualmente
    op.execute("UPDATE categorias SET estado = 'ACTIVO' WHERE estado = 1 OR estado = '1' OR estado = 'True'")
    op.execute("UPDATE categorias SET estado = 'INACTIVO' WHERE estado = 0 OR estado = '0' OR estado = 'False'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ACTIVO', 'INACTIVO', name='estadocategoria'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
