"""add empresa

Revision ID: f343dc781ad2
Revises: cd69a581a079
Create Date: 2026-06-23 11:00:53.683219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f343dc781ad2'
down_revision = 'cd69a581a079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=30), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sitio_web', sa.String(length=150), nullable=True),
    sa.Column('regimen', sa.String(length=80), nullable=True),
    sa.Column('serie_factura', sa.String(length=20), nullable=False),
    sa.Column('correlativo', sa.String(length=20), nullable=False),
    sa.Column('iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'ACTIVO'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'ACTIVO'"))

    op.drop_table('empresa')
    # ### end Alembic commands ###
