"""Agregar perfil de usuario

Revision ID: fd1f590f2887
Revises: 2a1dac0c398f
Create Date: 2026-07-24 12:40:07.610865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1f590f2887'
down_revision = '2a1dac0c398f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('telefono')
        batch_op.drop_column('genero')
        batch_op.drop_column('direccion')
        batch_op.drop_column('nombre_completo')

    # ### end Alembic commands ###
